---
final_name: cf-redis
min_cli_version: 1.5.0.pre.1113
blobstore:
  provider: s3
  options:
    bucket_name: redis-broker-bosh-release-blobs
    region: us-east-1
    credentials_source: env_or_profile
