meta:
  environment: YOUR_ENVIRONMENT_NAME
  external_domain: YOUR_CF_SYSTEM_DOMAIN
  apps_domain: YOUR_CF_APPS_DOMAIN
  nats:
    host: 10.10.16.11
    port: 4222
    username: NATS_USERNAME_FROM_CF_RELEASE
    password: NATS_PASSWORD_FROM_CF_RELEASE
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234

director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: redis_z1
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 8.8.8.8
    static:
    - 10.0.0.46
    - 10.0.0.47
    - 10.0.0.48
    - 10.0.0.49
    - 10.0.0.50
    - 10.0.0.51
    reserved:
    - 10.0.0.2-10.0.0.45
    - 10.0.0.63-10.0.0.254
    cloud_properties:
      name: YOUR_SUBNET_NAME #This should match your vSphere network name, e.g. "VM Network".

properties:
  redis:
    broker:
      backups: #Leave this section empty if you don't require backups.
        access_key_id: YOUR_S3_ACCESS_KEY_ID
        secret_access_key: YOUR_S3_SECRET_ACCESS_KEY 
        endpoint_url: S3_ENDPOINT_FOR_YOUR_REGION
        bucket_name: YOUR_S3_BUCKET
        path: YOUR_S3_BACKUP_PATH
  cf:
    admin_username: YOUR_CF_ADMIN_USERNAME
    api_url: https://api.YOUR_CF_SYSTEM_DOMAIN
    admin_password: YOUR_CF_ADMIN_PASSWORD

jobs:
- name: cf-redis-broker
  properties:
    broker:
      username: A_USERNAME_YOU_MAKE_UP
      password: A_PASSWORD_YOU_MAKE_UP
